FROM void-linux/void-glibc:latest 
WORKDIR /opt/workdir
ARG C_FLAGS="-Ofast -march=native \
	-flto -fno-signed-zeros \
	-fno-trapping-math -funroll-loops \
	-D_GLIBCXX_PARALLEL"
RUN xbps-install -Syu 
RUN xbps-install -y \
	cmake \
	extra-cmake-modules \
	gcc \
	ninja \
	qt5-devel \
	qtkeychain-qt5-devel \
	sqlite-devel \
	zlib-devel

CMD cmake -B target/release -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_FLAGS='$C_FLAGS' -G 'Ninja' && cmake --build target/release -j$(nproc)
